### ISSUE TITLE
Implement a refresh token logic

### ISSUE THREAD

**Issue by kkweon** [deep-diver/fb-group-post-fetcher#5]
I have tested and this flow seems to be working.

1. (one time only) Grab a user access token from Graph Explorer
2. Exchange it with a [long lived token](https://developers.facebook.com/docs/facebook-login/access-tokens/refreshing/)

```python
from typing import NamedTuple
import datetime

import aiohttp


class Token(NamedTuple):
    access_token: str
    token_type: str
    expires_in: datetime.datetime


async def refresh_token(app_id: str, app_secret: str, access_token: str) -> Token:
    """Exchanges access_token with a long term access token (expires in 60+ days)"""
    params = {
        "grant_type": "fb_exchange_token",
        "client_id": app_id,
        "client_secret": app_secret,
        "fb_exchange_token": access_token,
    }

    base_url = "https://graph.facebook.com/v7.0/oauth/access_token"

    async with aiohttp.ClientSession() as session:
        async with session.get(base_url, params=params) as resp:
            data = await resp.json()

            now = datetime.datetime.now()
            expires_in = now + datetime.timedelta(seconds=data["expires_in"])

            return Token(
                access_token=data["access_token"],
                token_type=data["token_type"],
                expires_in=expires_in,
            )
```

3. Update `.env` with a long access token so that now it can automate the process. It's important to keep the access token from being expired because an expired token cannot be refreshed. Since it's a long term access token, it has some buffer (60d) until it expires. Assuming it runs daily, it can be completely automated.

**Comment by deep-diver** [comment]
Let me clarify this process a bit.

Initial Phase
1. get a temporary access token from graph explorer
2. exchange the temporary access token with long lived access token
3. set the long lived access token in `.env`

Interative Phase
1. keep the long lived access token up until the expiration date
2. generate the other long lived access token from the current one
3. discard the current long lived access token, and replace it with the new one
4. decrypt the `.env` (gpg2)
5. set the new one in `.env`
6. encrypt the `.env` (gpg2)

correct?

**Comment by kkweon** [comment]
Initial Phase

1. get a temporary access token from graph explorer
   - short term token도 몇시간은 사용 가능하기 때문에 short term token을 굳이 long term 으로 바꿀 필요 없고 .env 에 로컬에서 저장 한 후 encrypt 푸시
2. ~exchange the temporary access token with long lived access token~  
3. ~set the long lived access token in .env~



Iterative Phase

0. decrypt  .env
1. 크론잡 daily 로 되있다고 가정하고
2. 매번 프로그램을 실행할때마다 .env 에 있는 토큰을 사용해 long term 으로 바로 변경합니다 (기존 토큰 사용 중지됨). 
3. 그 long term 으로 query 를 날리고 .env 에 저장합니다.
4. encrypt .env


이때, 0번과 4번은 파이썬 프로그램입장에서 몰라야 합니다. 파이썬 프로그램 외부에서 해야 되구요


```yaml
name: Send a newsletter.

on:
  schedule:
    # every hour.
    - cron: "0 * * * *"

  repository_dispatch:
    types: manual-trigger

jobs:
  newsletter:
    name: newsletter
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Decrypt .env.gpg => .env
        env:
          SYMMETRIC_KEY: ${{ secrets.SYMMETRIC_KEY }}
        run: gpg --quiet --batch --yes --decrypt --passphrase="$SYMMETRIC_KEY" --output=.env .env.gpg

      - name: Run the process
        run: export $(cat .env | xargs) && pipenv run python main.py

      - name: Encrypt .env => .env.gpg
        env:
          SYMMETRIC_KEY: ${{ secrets.SYMMETRIC_KEY }}
        run: echo "$SYMMETRIC_KEY" | gpg --symmetric --batch --passphrase-fd 0 .env

      - name: Push .env.gpg
        run: |
          git commit -am 'Updating .env.gpg'
          git push
```
